# Generated by Django 3.0.6 on 2020-06-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_display', '0002_profile_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pdf',
        ),
    ]
