# Generated by Django 3.0.6 on 2020-06-08 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_display', '0003_remove_profile_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdf'),
            preserve_default=False,
        ),
    ]
