# Generated by Django 3.0.6 on 2020-06-12 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_display', '0006_cert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cert',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
