# Generated by Django 3.0.6 on 2020-06-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_display', '0007_auto_20200612_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cert_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cert_summary',
        ),
    ]
