# Generated by Django 3.0.6 on 2020-06-12 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_display', '0008_auto_20200612_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cert_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cert_summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
