# Generated by Django 3.0.6 on 2020-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='image/')),
                ('cert_pdf', models.FileField(upload_to='pdf')),
                ('cert_summary', models.CharField(max_length=200)),
            ],
        ),
    ]
