# Generated by Django 3.0.6 on 2020-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20200613_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='image/')),
                ('cert_pdf', models.FileField(upload_to='pdf')),
                ('cert_summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='project_details',
        ),
    ]
