# Generated by Django 3.0.6 on 2020-06-13 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20200613_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_details',
            name='cert_detailed',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
