# Generated by Django 3.0.6 on 2020-06-13 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_details_cert_detailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_details',
            name='cert_backend',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate_details',
            name='cert_frontend',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
